### ISSUE TITLE
سوال درباره کلاس JsonNetResult 

### ISSUE THREAD

**Issue by moeinifar** [Dariush-Tasdighi/LEARNING_VUE#1]
سلام و وقت بخیر
سوالی که داشتم اینه که در کلاس JsonNetResult 
متد ExecuteResult 
برای System.Web.HttpResponseBase
متدی که در Core  وجود داره 
HttpResponse هستش ولی پراپرتی هایی مثل
ContentType و Output
براش وجود نداره
ممکنه راهنمایی بفرمایید در core چطورمیشه استفاده کرد
ممنون ازشما

**Comment by Dariush-Tasdighi** [comment]
سلام دوست من. در
Core
نیازی به این کلاس نیست! چون در نسخه
ASP.NET MVC
نتایج به صورت 
CamelCase
ارسال نمی‌شوند، من مجبور بودم که این کلاس را پیاده‌سازی کنم در صورتی که در 
Core
به صورت اتوماتیک و بدون نیاز به هیچ کلاسی، تمام داده‌ها به صورت
CamelCase
درآمده و ارسال می‌شوند
